### PR TITLE
New features and improvements

### LINKED ISSUE #8: Feature request: Add option to highlight major/minor/patch version in different colors
Example: major is red, minor is yellow, and patch is blue

### PR DESCRIPTION
**Pull request by rentalhost**
I spent a lot of time studying how vscode extensions work. It's pretty amazing. And with that I decided to make some nice improvements to `npm-outdated`. I hope I didn't miss the point.

Please tell me what you don't agree with so I can try to improve.

## Improved rendering time

In the _current version_, `^2.0`, packages are read all at once through `Promise.all()`, and only then is the first rendering done.

This prevents us from being able to show the user the outdates as quickly as possible. A project with 100 packages, for example, would take about 40~60 seconds to show outdated dependencies (at least on Windows).

I've made a nice change to how this all works. Now, as the information is being loaded, we take it to the user.

But calm down! It won't be a performance apocalypse. If the information starts to come in too fast, the plugin itself [will hold a few thousandths for the rendering](https://github.com/mskelton/vscode-npm-outdated/blob/2dbe897ddc63227833b86c3f650d23be0ec037b8/src/Utils.ts#L1-L55) to take place without affecting the overall performance of vscode.

## Improved resource consumption

In the _current version_, if we continue with our _100 dependencies example_, the plugin would create the `npm view` processes as fast as it could. This would consume a lot of resources. Okay that `npm view` uses very few resources, but if we think about everybody, maybe that could be a problem.

As a solution, [I limited the amount of processes that can happen in parallel](https://github.com/mskelton/vscode-npm-outdated/blob/2dbe897ddc63227833b86c3f650d23be0ec037b8/src/Utils.ts#L72-L97). By default, we can have up to 10 `npm view` processes running at a time. This option is configurable. If the user wants to keep how it worked before (and blow up your own computer itself), he can set it to `0` and that's it!

Of course, this will affect the finish time by a few seconds, but as an addendum to the previous topic, the user will already be able to follow the updates.

## Improved display of diagnostics

I didn't know, but when we define a code for `Diagnostic.code` it is displayed in _vscode_. As one of the solutions applied in the previous version, the result was a bit ugly.

Now the information is shown in a more elegant way, in addition to linking to the document that generated the diagnosis.

**Before:**

image

**After:**

image

## Light/dark theme support

I particularly use _light themes_, but it seems like I'm going against a big wave. The plugin will now color the decorations according to the user's theme.

"Wait, did you say... decorations?"

## Yes, decorations

One of the new features is support for decorations. They manage to visually represent (without depending on the mouse hover on the diagnostics) the situation of a package.

**It fixes #8.**

image

image

image

image

**The decorations will show:**

* A subtle "checking" indicator;
* If the package is outdated;
* Whether the intended update will perform a _major dump_;
* If the package was never installed (and therefore it will be);
* If the latest package is already installed, and it is only necessary to "_formalize_" it in `package.json`;

Decorations can be disabled (_but who would be the monster that would do that?_).

## Protection against major updates

Upgrading a package to its _major version_ can be a problem as it can cause _breaking-changes_. In this case, we have a new setting that allows you to protect against accidental major updates (for example, when using the "_update all packages_" action), enabled by _default_.

Updates will occur in "_layers_" in this case.

Let's assume that you have set version `^3.0`, and have in fact installed version `3.1.5`. However, there is a new version available `3.2.0` and also a new major version `4.0.0`. Before, when accepting the update suggestion, the package would be updated directly to the `4.0.0` version, which maybe wasn't ideal for the user.

However, with protection enabled, the plugin will suggest the user to update to version `^3.2.0` first and, after acceptance, will suggest the major version (with a warning).

## Pre-release support

If the user is intentionally using a _pre-release version_ (eg `next: ^13.0.8-canary.0`) and a new version becomes available, the plugin will suggest it (keeping it in pre-release, eg. `^13.0.8-canary.1`). However, if the final version `13.0.8` or higher becomes available, it will be suggested.

A next pre-release version is never suggested in this case, only if it is "_the same base version_". For example: `^13.0.8-canary.0` might suggest `^13.0.8-canary.1`, but it won't suggest `^13.0.9-canary.0` (in this case it will suggest `^13.0. 8` "final").

## Multi-locale support

In addition to _english_, it will now be possible to translate the plugin into other languages. For now, it can be used in english or portuguese (Brazil), which is my native language.

Also, it would be interesting for you to check if I made any mistakes in english ([1](https://github.com/mskelton/vscode-npm-outdated/blob/feature/decorations-support/locales/bundle.l10n.jsonc) and [2](https://github.com/mskelton/vscode-npm-outdated/blob/feature/decorations-support/package.nls.json)). Perhaps you have noticed that it is not the best. (Okay, I'm using Google Translator right now, but that's because it's a lot of text!)

## Optimization using esbuild

The final package should now be optimized using `esbuild`. I still don't know how it will behave when pushed to the `main` branch, but I believe it will work fine.

As a result, we have a code that occupies 1/3 of the previous size (and that's considering that the source code has increased a lot with all the news)!

Also, because the code is better organized, it will probably bring results in the overall performance of the plugin.

## Other minor improvements

* Ability to update versions using other prefixes: `^`, `~`, `>=` etc.
* Updating packages via selection got smarter, including warnings like "_updating major_" or "_excluding major_" (when protection is enabled).
* Recognize invalid or never released versions of a package (performance gain, as you don't need to run `npm view` until this is resolved).
* Watch for updates to `package-lock.json` to perform new diagnostics.
* Icon optimization (it's the same but optimized), reducing 89% of the original size.
* Avoid re-diagnostics in unnecessary cases.
* Ignore complex versioning (eg `>=13.0 <13.1.5`). It's hard to understand to be able to suggest something.
* Improvements to the plugin development environment, as to disable other plugins temporarily to make it activate faster.
* Don't suggest `npm install` when unnecessary (eg version already installed and just updating `packages.json`).

I think that's all!

---

image

image

image

image

image

image

image

image

### CODE REVIEW

**Comment by rentalhost** [comment]
Oh, and most importantly!

## Why a super PR?

The reality is that I just wanted to implement support for decorations (you can note the branch name). But I realized that it would not be possible to do only this support without redoing or optimizing a good part of the code.

Before I realized it, I had already made a lot of modifications, and so I decided to make the other modifications that I intended to make in the future (via other PRs).

I failed miserably, but I believe it was a good failure.

**Comment by rentalhost** [comment]
## Tests

Implemented a test suite via jest, including 100% coverage (with only 1 intentional ignore).

**Comment by rentalhost** [comment]
And the last one... I guess:

## Security advisories support

Through the NPM Registry API it was possible to verify if the packages in use have some type of security advisory. The plugin will suggest a version that has a fix or a downgrade.

---

Before you review all, I'm trying to fix two problems I've run into just now.

**Comment by InfamousStarFox** [comment]
Regarding the `npm view` child process issue, why not use `npm outdated --json` instead?

**Comment by rentalhost** [comment]
@InfamousStarFox The `npm outdated` command only displays already installed packages that are outdated. By otherside, `npm view` command can get all released versions of the package, so we can check as the user types (without having to install anything before). This way the plugin can work much more adequate and with complete information compared to `npm outdated`.

**Comment by rentalhost** [comment]
Well, now I think I've completed everything I wanted to. I believe the plugin is complete and there is probably very little to do beyond that. :') @mskelton Can you please review that for me? As this PR got too long, there are some comments hidden by github. If you want more details too, some commits have descriptions explaining better the "why of things".

## Checked icon

To make it easier for the user to read, packages that are verified without errors and already in their respective latest versions are displayed with a ✓.

image

## Even more performance via Registry NPM

Instead of using `npm view`, it is possible to access the same information directly from the NPM Registry API. This increases the checkin speed by about 5 times!

However, private repositories will still rely on `npm view` and it will be used as a fallback automatically.

**Review by mskelton — APPROVED** [review]
Sounds like a lot of good changes!  Thanks for helping bring this extension back into stability.

**Pull request merged**
